### ISSUE TITLE
Canva.js

### ISSUE THREAD

**Issue by Aissoquatre** [cocoa-wafer/slider#3]
Refactoriser le code : transformer les function en méthode, créer plus d'attributs et stocker, entre autre, des objets jQuery dedans pour éviter de les recréer à la volée à chaque fois (canvas, boutons, ...)

**Comment by cocoa-wafer** [comment]
J'ai transformé toute les fonctions en méthodes, par contre je ne comprends pas la deuxième partie du commentaire; 
est ce que tu fais référence à le redondance des "document.getElementById()" ? dans le sens ou tu voudrais que je déclare des variables au début des méthodes type var a = document.getelementById('a') pour ensuite les manipuler type a.innerHTML etc ?

**Comment by Aissoquatre** [comment]
Je parle de tous les document.createElement(), mais en l'état avec ta refacto c'est pas forcément choquant.
Attention par contre à ton indentation de code.

**Comment by cocoa-wafer** [comment]
est ce que çà te va comme çà ?

**Comment by Aissoquatre** [comment]
Tu as encore une fonction dans une méthode, et tu peux encore très largement refactoriser le code de tes méthodes, elles sont bien trop longues.

**Comment by cocoa-wafer** [comment]
Qu'est ce que tu en dis ?

**Comment by Aissoquatre** [comment]
C'est mieux !
Utilise le this plutôt que de faire Canva.maMethode(), et évidemment attention au contexte.
Après ça on est bon.

**Comment by cocoa-wafer** [comment]
Je pense que c'est bon

**Comment by Aissoquatre** [comment]
Il t'en reste 14 encore, fais un ctrl + F de Canva. pour les identifier !

**Comment by cocoa-wafer** [comment]
Les 14 restants sont dans des événements.
Du coup this renvoie l'élément qui déclenche l'événement et plus l'objet Canva. 
idem, dans diminuerCompteur(), this renvoie à Window().

je pensais que c'était çà dont tu parlais quand tu disais de faire attention au contexte.
est ce que créer une variable _this = this dans la méthode, en dehors des events, pour ensuite utiliser _this.maMéthode() est acceptable ? 
je ne vois pas comment procéder autrement.

**Comment by Aissoquatre** [comment]
Oui faire attention au contexte veut dire que quand tu changes de contexte (evenement, ou autre) tu dois avant tout stocker le this dans une variable pour la réutiliser après.
Surtout que tu l'as déjà fait !

**Comment by cocoa-wafer** [comment]
est ce que çà te va ?

**Comment by Aissoquatre** [comment]
Rien n'a changé.

**Comment by cocoa-wafer** [comment]
désolée effectivement mon push n'avait pas fonctionné. 
normalement c'est visible maintenant.
